swagger: '2.0'
info:
  version: 1.0.0
  title: TodoApi
  description: |
    Find source code of this API [here](https://github.com/antferman3/cbd-14)
host: https://pruebacovid23.herokuapp.com/
consumes:
  - application/json
produces:
  - application/json
paths:
  /todos/{id}:
    get:
      parameters:
        - name: id
          in: path
          description: number of pets to return
          required: true
          type: integer
          format: int64
      responses:
        200:
          description:  Get todo by Id
          schema:
            $ref: '#/definitions/todo'
definitions:
  todo:
    type: object
    properties:
      id:
        type: integer
        format: int64
      description:
        type: string